### ISSUE TITLE
Recaptcha verification destroys JSON marshallers

### ISSUE THREAD

**Issue by sarbogast** [iamthechad/grails3-recaptcha#22]
I'm using quite a few JSON marshallers registered in my bootstrap, and the problem is that RecaptchaService is using a brand new RestBuilder to call Google's verification API, and when RestBuilder is created like that, it blows up all JSON marshallers already registered. I don't know what the solution would be, maybe instantiate RestBuilder with `registerConverters: false` in the settings to prevent it from overriding JSON marshallers, but that setting is only available in the latest version of grails-datastore-rest-client.

**Comment by iamthechad** [comment]
Looks like this is because of https://github.com/grails/grails-data-mapping/issues/864

**Comment by sarbogast** [comment]
It most definitely is. And as you can see, James Kleeh recently added a flag to the RestBuilder constructor to work around that issue. But you have to use it.

**Comment by iamthechad** [comment]
Is there a simple example project I can reference so I can reproduce this issue?
